---
name: Deploy to Production Amazon ECS

on:
  workflow_dispatch: # Add this line to enable manual triggering

env:
  AWS_REGION: ap-southeast-2
  AWS_ACCOUNT_ID: "026148122259"

permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/GithubActionsRole
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}
      - name: Checkout code
        run: aws events put-events --entries 'Source=action.production,DetailType=DEPLOY,Detail="{\"service\":\"backend\"}",EventBusName=default'